<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.timevale</groupId>
        <artifactId>mandarin-pure-bom</artifactId>
        <version>2.11.6.5</version>
    </parent>

    <groupId>com.timevale.forward</groupId>
    <artifactId>forward-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>forward/Parent</name>
    <url>https://www.tsign.cn/</url>
    <description>forward Application Parent</description>

    <modules>
        <module>dal</module>
        <module>facade</module>
        <module>model</module>
        <module>service</module>
        <module>deploy</module>
    </modules>

    <properties>
        <!-- Third Party -->
        <guava.version>31.1-jre</guava.version>
        <hutool.version>5.7.13</hutool.version>
        <testng.version>6.14.3</testng.version>
        <aspectj.version>1.9.4</aspectj.version>
        <easyexcel.version>2.2.8</easyexcel.version>
        <collections4.version>4.4</collections4.version>
        <mapstruct.version>1.4.2.Final</mapstruct.version>
        <swagger-bootstrap-ui.version>1.8.8</swagger-bootstrap-ui.version>
        <springfox-swagger2.version>2.9.2</springfox-swagger2.version>
        <!-- Second Party -->
        <mq.version>2.11.2</mq.version>
        <elock.version>1.2.1</elock.version>
        <tedis.version>1.1.0-RELEASE</tedis.version>
        <schedulerT.version>2.1.0</schedulerT.version>
        <footstone-base.version>1.0.0-SNAPSHOT</footstone-base.version>
        <billing-log-monitor.version>1.2.9-SNAPSHOT</billing-log-monitor.version>
        <crm-sdk-common-core-version>1.0.11-SNAPSHOT</crm-sdk-common-core-version>
        <!-- RPC Facade -->
        <epeius.version>1.0.0-SNAPSHOT</epeius.version>
        <lowcode.version>0.0.1-SNAPSHOT</lowcode.version>
        <crm-dock.version>2.0.7-SNAPSHOT</crm-dock.version>
        <filesystem.version>2.0.4-RELEASE</filesystem.version>
        <erp.message-facade.version>1.2.6-SNAPSHOT</erp.message-facade.version>
        <custom-provider-facade.version>2.4.1-SNAPSHOT</custom-provider-facade.version>
        <inuser.security.facade.version>1.1.18-SNAPSHOT</inuser.security.facade.version>
        <encourage-facade.version>1.0.0-SNAPSHOT</encourage-facade.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- 基础模型 -->
            <dependency>
                <groupId>com.timevale.footstone-base</groupId>
                <artifactId>footstone-base-model</artifactId>
                <version>${footstone-base.version}</version>
                <exclusions>
                    <exclusion>
                        <artifactId>mandarin-common</artifactId>
                        <groupId>com.timevale</groupId>
                    </exclusion>
                </exclusions>
            </dependency>
            <!--文件服务-->
            <dependency>
                <groupId>com.timevale.filesystem</groupId>
                <artifactId>filesystem-common-service-facade</artifactId>
                <version>${filesystem.version}</version>
            </dependency>
            <!--对象映射工具-->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <!--警告日志到群-->
            <dependency>
                <groupId>com.timevale.billing</groupId>
                <artifactId>basicbs-billing-log-monitor</artifactId>
                <version>${billing-log-monitor.version}</version>
            </dependency>
            <!-- reids -->
            <dependency>
                <groupId>com.timevale.spring.boot</groupId>
                <artifactId>tedis-spring-boot-starter</artifactId>
                <version>${tedis.version}</version>
            </dependency>
            <!-- schedulerT -->
            <dependency>
                <groupId>com.timevale.framework</groupId>
                <artifactId>schedulerT-client</artifactId>
                <version>${schedulerT.version}</version>
            </dependency>
            <!-- mq -->
            <dependency>
                <groupId>com.timevale.spring.boot</groupId>
                <artifactId>esign-mq-spring-boot-starter</artifactId>
                <version>${mq.version}</version>
            </dependency>
            <!-- 内部用户中心-->
            <dependency>
                <groupId>com.timevale.security</groupId>
                <artifactId>facade</artifactId>
                <version>${inuser.security.facade.version}</version>
            </dependency>
            <!-- 客户-->
            <dependency>
                <groupId>com.timevale.crm.custom-provider</groupId>
                <artifactId>custom-provider-facade</artifactId>
                <version>${custom-provider-facade.version}</version>
            </dependency>
            <!-- 交付项目 -->
            <dependency>
                <groupId>com.timevale.crm.dock</groupId>
                <artifactId>crm-dock-facade</artifactId>
                <version>${crm-dock.version}</version>
            </dependency>
            <!-- erp消息 -->
            <dependency>
                <groupId>com.timevale.erp.message</groupId>
                <artifactId>erp.message-facade</artifactId>
                <version>${erp.message-facade.version}</version>
            </dependency>
            <!-- 分布式锁 -->
            <dependency>
                <groupId>com.timevale.spring.boot</groupId>
                <artifactId>elock-spring-boot-starter</artifactId>
                <version>${elock.version}</version>
            </dependency>
            <!-- swagger -->
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger-ui</artifactId>
                <version>${springfox-swagger2.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>swagger-bootstrap-ui</artifactId>
                <version>${swagger-bootstrap-ui.version}</version>
            </dependency>
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger2</artifactId>
                <version>${springfox-swagger2.version}</version>
            </dependency>

            <!-- 单元测试 -->
            <dependency>
                <groupId>org.aspectj</groupId>
                <artifactId>aspectjweaver</artifactId>
                <version>${aspectj.version}</version>
            </dependency>
            <dependency>
                <groupId>org.testng</groupId>
                <artifactId>testng</artifactId>
                <version>${testng.version}</version>
            </dependency>

            <!-- 工具 -->
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>

            <!-- epeius 工作流 -->
            <dependency>
                <groupId>com.timevale.epeius</groupId>
                <artifactId>epeius-facade</artifactId>
                <version>${epeius.version}</version>
            </dependency>

            <dependency>
                <groupId>com.timevale.lowcode</groupId>
                <artifactId>support-flow-facade</artifactId>
                <version>${lowcode.version}</version>
            </dependency>

            <!-- Excel工具 -->
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>easyexcel</artifactId>
                <version>${easyexcel.version}</version>
            </dependency>

            <dependency>
                <groupId>com.timevale.crm.sdk</groupId>
                <artifactId>crm-sdk-common-core</artifactId>
                <version>${crm-sdk-common-core-version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>${collections4.version}</version>
            </dependency>

            <dependency>
                <groupId>com.timevale.encourage</groupId>
                <artifactId>encourage-facade</artifactId>
                <version>${encourage-facade.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>
</project>
