env=TEST
test.meta=http://172.20.61.183:7001
pre.meta=http://47.99.224.235:7001
prod.meta=http://172.28.90.126:7001
app.id=forward
puppeteer.bootstrap.enabled=true
puppeteer.bootstrap.namespaces=application,JSBZ.SOA_PUBLIC
